package orchestrator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/clishakehq/clishake/internal/domain"
)

// The context directory (.clishake/context/) is the file-based session
// context shared with every agent — the same idea as a CLAUDE.md, but
// session-scoped and kept current by clishake itself:
//
//	session.md  — project, session identity, communication protocol
//	roster.md   — live agent roster with roles/status/branches
//	tasks.md    — the shared task board
//	notes.md    — append-only shared notes & decisions (clishake note)
//
// The launch briefing points agents at these files so they can re-read
// fresh context at any time instead of relying on a launch-time snapshot.

// ContextDir returns the context directory path for the project.
func (o *Orchestrator) ContextDir() string {
	return filepath.Join(ClishakeDir(o.ProjectDir), "context")
}

// syncContext rewrites the generated context files from current state.
// Failures are non-fatal (context files are an aid, not a dependency).
func (o *Orchestrator) syncContext() {
	dir := o.ContextDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	_ = os.WriteFile(filepath.Join(dir, "session.md"), []byte(o.sessionMD()), 0o644)
	_ = os.WriteFile(filepath.Join(dir, "roster.md"), []byte(o.rosterMD()), 0o644)
	_ = os.WriteFile(filepath.Join(dir, "tasks.md"), []byte(o.tasksMD()), 0o644)
	notes := filepath.Join(dir, "notes.md")
	if _, err := os.Stat(notes); os.IsNotExist(err) {
		_ = os.WriteFile(notes, []byte("# Shared notes & decisions\n\nAppend with: clishake note \"...\"\n"), 0o644)
	}
}

// watchContext subscribes syncContext to the events that change what the
// context files describe. Message traffic is deliberately excluded — it is
// high-volume and already visible via `clishake messages`.
func (o *Orchestrator) watchContext() {
	o.Log.Subscribe(func(ev domain.Event) {
		t := string(ev.Type)
		if strings.HasPrefix(t, "agent.") || strings.HasPrefix(t, "task.") ||
			strings.HasPrefix(t, "session.") || strings.HasPrefix(t, "approval.") ||
			strings.HasPrefix(t, "config.") {
			o.syncContext()
		}
	})
}

func (o *Orchestrator) sessionMD() string {
	bin := clishakeBin()
	var b strings.Builder
	b.WriteString("# clishake session\n\n")
	fmt.Fprintf(&b, "- Project: %s\n- Session: %s\n- Tmux session: %s (socket %q)\n- Updated: %s\n\n",
		o.ProjectDir, o.Session.ID, o.Cfg.SessionName(), o.Cfg.Tmux.Socket,
		time.Now().UTC().Format(time.RFC3339))
	b.WriteString("## Communication protocol\n\n")
	b.WriteString("- The human team lead is addressed as \"lead\" and supervises everything.\n")
	fmt.Fprintf(&b, "- Message anyone: `%s send @<recipient> \"...\"` (recipients: lead, an agent name, @role:<r>, @team:<t>, @all).\n", bin)
	fmt.Fprintf(&b, "- Inspect the session: `%s agents` · `%s tasks` · `%s messages` · `%s events`.\n", bin, bin, bin, bin)
	fmt.Fprintf(&b, "- Report task progress: `%s task update <task-id> --status in_progress|completed --summary \"...\"`.\n", bin)
	fmt.Fprintf(&b, "- Record a shared note/decision: `%s note \"...\"`.\n", bin)
	b.WriteString("- Messages arriving in your terminal prefixed `[clishake message from <sender>]` are routed session traffic.\n")
	b.WriteString("- Files in this directory are regenerated by clishake; re-read them for fresh context. Only notes.md persists manual entries.\n")
	return b.String()
}

func (o *Orchestrator) rosterMD() string {
	agents, err := o.Store.ListAgents()
	var b strings.Builder
	b.WriteString("# Agent roster (live)\n\n")
	if err != nil || len(agents) == 0 {
		b.WriteString("No agents registered.\n")
		return b.String()
	}
	byID := map[string]*domain.Agent{}
	for _, a := range agents {
		byID[a.ID] = a
	}
	for _, a := range agents {
		parent := ""
		if a.ParentID != "" && byID[a.ParentID] != nil {
			parent = fmt.Sprintf(" (sub-agent of %s)", byID[a.ParentID].Name)
		}
		task := ""
		if a.Task != "" {
			task = " — task: " + a.Task
		}
		branch := ""
		if a.Branch != "" {
			branch = fmt.Sprintf(" — branch %s in %s", a.Branch, a.WorkDir)
		}
		fmt.Fprintf(&b, "- **%s** (role: %s, harness: %s) status: %s%s%s%s\n",
			a.Name, orDash(a.Role), a.Adapter, a.Status, parent, branch, task)
	}
	return b.String()
}

func (o *Orchestrator) tasksMD() string {
	tasks, err := o.Tasks.List()
	var b strings.Builder
	b.WriteString("# Shared task board\n\n")
	if err != nil || len(tasks) == 0 {
		b.WriteString("No tasks yet.\n")
		return b.String()
	}
	sorted := append([]*domain.Task{}, tasks...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Priority > sorted[j].Priority })
	for _, t := range sorted {
		owner := t.Owner
		if owner == "" {
			owner = "unassigned"
		}
		fmt.Fprintf(&b, "- %s [%s → %s] %s", t.ID, t.Status, owner, t.Title)
		if t.Description != "" {
			fmt.Fprintf(&b, " — %s", t.Description)
		}
		if len(t.DependsOn) > 0 {
			fmt.Fprintf(&b, " (depends on %s)", strings.Join(t.DependsOn, ", "))
		}
		if t.Summary != "" {
			fmt.Fprintf(&b, " — done: %s", t.Summary)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// AddNote appends an attributed entry to notes.md and emits an event.
func (o *Orchestrator) AddNote(author, text string) error {
	if strings.TrimSpace(text) == "" {
		return fmt.Errorf("empty note")
	}
	o.syncContext() // ensure the directory and notes.md exist
	f, err := os.OpenFile(filepath.Join(o.ContextDir(), "notes.md"),
		os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	line := fmt.Sprintf("- %s **%s**: %s\n",
		time.Now().UTC().Format("2006-01-02 15:04"), author, strings.ReplaceAll(text, "\n", " "))
	if _, err := f.WriteString(line); err != nil {
		return err
	}
	o.emit(domain.EvNoteAdded, author, "notes.md", map[string]any{"text": truncate(text, 200)})
	return nil
}
